services:
    # Update this to the name of the service you want to work with in your docker-compose.yml file
    app:
        hostname: "hello_world_app"
        container_name: "hello_world_app"
        # Uncomment if you want to override the service's Dockerfile to one in the .devcontainer
        # folder. Note that the path of the Dockerfile and context is relative to the *primary*
        # docker-compose.yml file (the first in the devcontainer.json "dockerComposeFile"
        # array). The sample below assumes your primary file is in 'docker' folder at the root of your project.
        #
        build:
            # context must be given in relation to Dockerfile
            context: ..
            dockerfile: ./docker/dockerfile
            target: devcontainer

        volumes:
        # Update this to wherever you want VS Code to mount the folder of your project
        - ..:/opt/app/:cached

        depends_on:
        - db

        ports:
        - "8001:8000"

        env_file:
        - ../.env
        - ../.devcontainer/.env

        # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
        # cap_add:
        #   - SYS_PTRACE
        # security_opt:
        #   - seccomp:unconfined

        # Overrides default command so things don't shut down after the process ends.
        command: sleep infinity
    
    db:
        hostname: "hello_world_db"
        container_name: "hello_world_db"
        image: "postgres:15-alpine"
        ports:
        - "5432:5432"
        volumes:
        - ./postgres_bootstrap:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}